/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {}
export type ExecuteMsg = {
  create: {
    counter_offer: Coin[];
    time_stamp: number;
  };
} | {
  transfer: {
    id: number;
    to: string;
  };
} | {
  execute: {
    id: number;
  };
} | {
  burn: {
    id: number;
  };
} | {
  claim_collateral: {
    id: number;
  };
} | {
  split: {
    id: number;
    percentage: number;
  };
} | {
  approve: {
    spender: string;
  };
} | {
  dis_approve: {
    spender: string;
  };
};
export type Uint128 = string;
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export type QueryMsg = {
  config: {};
} | {
  options: {};
} | {
  options_page: {
    amount: number;
    key: number;
  };
} | {
  get_option_byid: {
    id: number;
  };
} | {
  createor_options: {
    addr: string;
  };
} | {
  owner_options: {
    addr: string;
  };
} | {
  get_is_approve: {
    owner: string;
    spender: string;
  };
};
export type Addr = string;
export interface State {
  owner: Addr;
  total_options_amount: number;
}
export type Timestamp = Uint64;
export type Uint64 = string;
export type ArrayOfTupleOfUint64AndData = [number, Data][];
export interface Data {
  collateral: Coin;
  counter_offer: Coin;
  creator: Addr;
  expires: Timestamp;
  isBurned: boolean;
  owner: Addr;
}
export type Boolean = boolean;