/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {}
export type ExecuteMsg = {
  create: {
    counter_offer: Coin[];
    time_stamp: number;
  };
} | {
  add_to_market: {
    amount: string;
    denom: string;
    id: number;
  };
} | {
  remove_from_market: {
    id: number;
  };
} | {
  buy: {
    id: number;
  };
} | {
  update_price: {
    id: number;
    price: Coin[];
  };
} | {
  transfer: {
    id: number;
    to: string;
  };
} | {
  execute: {
    id: number;
  };
} | {
  burn: {
    id: number;
  };
} | {
  claim: {
    id: number;
  };
};
export type Uint128 = string;
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export type QueryMsg = {
  config: {};
} | {
  options: {};
} | {
  options_page: {
    amount: number;
    key: number;
  };
} | {
  get_option_byid: {
    id: number;
  };
} | {
  market_options: {};
} | {
  maket_options_pagee: {
    amount: number;
    key: number;
  };
} | {
  createor_options: {
    addr: string;
  };
} | {
  owner_options: {
    addr: string;
  };
};
export type Addr = string;
export interface State {
  creator: Addr;
  total_options_num: number;
}
export type Timestamp = Uint64;
export type Uint64 = string;
export type ArrayOfTupleOfUint64AndData = [number, Data][];
export interface Data {
  collateral: Coin[];
  counter_offer: Coin[];
  creator: Addr;
  expires: Timestamp;
  onsale: boolean;
  owner: Addr;
  price: Coin[];
}