/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { InstantiateMsg, ExecuteMsg, Uint128, Coin, QueryMsg, Addr, State, Timestamp, Uint64, ArrayOfTupleOfUint64AndData, Data, Boolean } from "./Constellation.types";
export interface ConstellationReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<State>;
  options: () => Promise<ArrayOfTupleOfUint64AndData>;
  optionsPage: ({
    amount,
    key
  }: {
    amount: number;
    key: number;
  }) => Promise<ArrayOfTupleOfUint64AndData>;
  getOptionByid: ({
    id
  }: {
    id: number;
  }) => Promise<Data>;
  createorOptions: ({
    addr
  }: {
    addr: string;
  }) => Promise<ArrayOfTupleOfUint64AndData>;
  ownerOptions: ({
    addr
  }: {
    addr: string;
  }) => Promise<ArrayOfTupleOfUint64AndData>;
  getIsApprove: ({
    owner,
    spender
  }: {
    owner: string;
    spender: string;
  }) => Promise<Boolean>;
}
export class ConstellationQueryClient implements ConstellationReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.options = this.options.bind(this);
    this.optionsPage = this.optionsPage.bind(this);
    this.getOptionByid = this.getOptionByid.bind(this);
    this.createorOptions = this.createorOptions.bind(this);
    this.ownerOptions = this.ownerOptions.bind(this);
    this.getIsApprove = this.getIsApprove.bind(this);
  }

  config = async (): Promise<State> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  options = async (): Promise<ArrayOfTupleOfUint64AndData> => {
    return this.client.queryContractSmart(this.contractAddress, {
      options: {}
    });
  };
  optionsPage = async ({
    amount,
    key
  }: {
    amount: number;
    key: number;
  }): Promise<ArrayOfTupleOfUint64AndData> => {
    return this.client.queryContractSmart(this.contractAddress, {
      options_page: {
        amount,
        key
      }
    });
  };
  getOptionByid = async ({
    id
  }: {
    id: number;
  }): Promise<Data> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_option_byid: {
        id
      }
    });
  };
  createorOptions = async ({
    addr
  }: {
    addr: string;
  }): Promise<ArrayOfTupleOfUint64AndData> => {
    return this.client.queryContractSmart(this.contractAddress, {
      createor_options: {
        addr
      }
    });
  };
  ownerOptions = async ({
    addr
  }: {
    addr: string;
  }): Promise<ArrayOfTupleOfUint64AndData> => {
    return this.client.queryContractSmart(this.contractAddress, {
      owner_options: {
        addr
      }
    });
  };
  getIsApprove = async ({
    owner,
    spender
  }: {
    owner: string;
    spender: string;
  }): Promise<Boolean> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_is_approve: {
        owner,
        spender
      }
    });
  };
}
export interface ConstellationInterface extends ConstellationReadOnlyInterface {
  contractAddress: string;
  sender: string;
  create: ({
    counterOffer,
    timeStamp
  }: {
    counterOffer: Coin[];
    timeStamp: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  transfer: ({
    id,
    to
  }: {
    id: number;
    to: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  execute: ({
    id
  }: {
    id: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  burn: ({
    id
  }: {
    id: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  claimCollateral: ({
    id
  }: {
    id: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  split: ({
    id,
    percentage
  }: {
    id: number;
    percentage: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  approve: ({
    spender
  }: {
    spender: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  disApprove: ({
    spender
  }: {
    spender: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class ConstellationClient extends ConstellationQueryClient implements ConstellationInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.create = this.create.bind(this);
    this.transfer = this.transfer.bind(this);
    this.execute = this.execute.bind(this);
    this.burn = this.burn.bind(this);
    this.claimCollateral = this.claimCollateral.bind(this);
    this.split = this.split.bind(this);
    this.approve = this.approve.bind(this);
    this.disApprove = this.disApprove.bind(this);
  }

  create = async ({
    counterOffer,
    timeStamp
  }: {
    counterOffer: Coin[];
    timeStamp: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      create: {
        counter_offer: counterOffer,
        time_stamp: timeStamp
      }
    }, fee, memo, _funds);
  };
  transfer = async ({
    id,
    to
  }: {
    id: number;
    to: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      transfer: {
        id,
        to
      }
    }, fee, memo, _funds);
  };
  execute = async ({
    id
  }: {
    id: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      execute: {
        id
      }
    }, fee, memo, _funds);
  };
  burn = async ({
    id
  }: {
    id: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      burn: {
        id
      }
    }, fee, memo, _funds);
  };
  claimCollateral = async ({
    id
  }: {
    id: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      claim_collateral: {
        id
      }
    }, fee, memo, _funds);
  };
  split = async ({
    id,
    percentage
  }: {
    id: number;
    percentage: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      split: {
        id,
        percentage
      }
    }, fee, memo, _funds);
  };
  approve = async ({
    spender
  }: {
    spender: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      approve: {
        spender
      }
    }, fee, memo, _funds);
  };
  disApprove = async ({
    spender
  }: {
    spender: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      dis_approve: {
        spender
      }
    }, fee, memo, _funds);
  };
}