/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Consteallation.types";
import * as _1 from "./Consteallation.client";
import * as _2 from "./Consteallation.message-composer";
import * as _3 from "./Consteallation.react-query";
import * as _4 from "./Consteallation.recoil";
export namespace contracts {
  export const Consteallation = { ..._0,
    ..._1,
    ..._2,
    ..._3,
    ..._4
  };
}